### ISSUE TITLE
Error deploying in OpenShift because of chown

### ISSUE THREAD

**Issue by bennyevangelista** [dzikoysk/reposilite#1657]
### What happened?

Hi, I'm trying to setup a POC of Reposilite for my organization, it runs perfectly via podman on my development machine,  but when I try to deploy it in an openshift cluster the pod crashes right after the start. Below you will find the log entries before the crash, and here's my deployment yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-reposilite
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: reposilite
  template:
    metadata:
      labels:
        deployment: reposilite
    spec:      
      containers:      
      - name: reposilite
        image: dzikoysk/reposilite:3.2.0       
        ports:
        - containerPort: 8080
          name: tcp-8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256M  
```   

Does the container need root priviliges to run? In this case this would break one of my company's security policy.

Thanks for the support!

### Reposilite version

3.x

### Relevant log output

```shell
chown: changing ownership of '/app/data/lost+found': Operation not permitted
chown: changing ownership of '/app/data': Operation not permitted
chown: changing ownership of '/app/entrypoint.sh': Operation not permitted
chown: changing ownership of '/app/reposilite.jar': Operation not permitted
chown: changing ownership of '/app': Operation not permitted
chown: changing ownership of '/var/log/reposilite': Operation not permitted
runuser: may not be used by non-root users
```
