### ISSUE TITLE
Minio S3 Documentation

### ISSUE THREAD

**Issue by topi314** [dzikoysk/reposilite#1799]
### Request details

There should be a minio s3 section in the docs.

Here is how it will work:
add`-Dreposilite.s3.pathStyleAccessEnabled=true` to your jvm options (`JAVA_OPTS` env variable for docker)

```yaml
bucket: your-bucket
endpoint: http://minio:9000 # your minio endpoint
access-key: your-access-key
secret-key: your-secret-key
region: doesn't matter
```

For context: https://discord.com/channels/204728244434501632/875148821842231296/1102284265569386546
