### ISSUE TITLE
Automated date based cleanup option for mirrored artifacts

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#2074]
Initially requested for Reposilite 4.x by @solonovamax:

> with this, you'd also be able to provide the following things:
>
>   add a badge on remote artifacts/modules to indicate they're from a mirror (& maybe which mirror they're from?)
>   allow administrators to set storage limits on mirrored artifacts and use smth like an LRU policy to discard old cached artifacts.

~ https://github.com/dzikoysk/reposilite/issues/2005#issuecomment-1981698246

**Comment by solonovamax** [comment]
I think it's also important to highlight this part (ie. this feature depends on adding the ability to set the storage to an external location, as it'd make it quite a lot easier to measure the size of all artifacts cached from a mirrored repo)

> smth I thought of a while back that would be nice is: the ability to store cached files from a proxied/mirrored repository in a separate location.
>
> so, for example, the contents of the `releases` (that have been uploaded directly to the repo) repo could be stored in `repo/releases`.
> but then, say you're mirroring `foo.com` and `bar.net` (and reposilite is configured to store those artifacts)
> then, the artifacts from each of those would be located in smth like `mirrors/releases/foo.com` and `mirrors/releases/bar.net`.

**Comment by jonasfa** [comment]
While Reposilite doesn't offer mirror pruning out of the box, I've implemented it with a shell script on Docker Compose:

```yaml
services:
  reposilite:
    image: dzikoysk/reposilite:latest
    volumes:
      - reposilite-data:/app/data
    ...

  reposilite-pruner:
    image: ubuntu:latest
    depends_on:
      - reposilite
    volumes:
      - reposilite-data:/app/data
    command:
      - sh
      - -c
      - |
        trap 'exit 0' TERM
        while true; do
          date -Iseconds
          find /app/data/repositories -type f -atime +14 -print -delete
          sleep 1h & wait $!
        done

volumes:
  reposilite-data:
```

Notes:
- All my repositories are mirrors, so I just prune them all without filtering
- Alpine's (BusyBox) `find -atime` doesn't seem to work, thus I went with Ubuntu (GNU find)
